[tasks.build-js]
command = "wasm-pack"
args = ["build", "--release"]

[tasks.build-web]
command = "wasm-pack"
args = ["build", "--release", "--target", "no-modules", "-d", "web"]

[tasks.js]
dependencies = ["build-js", "build-web"]
